---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install ansible
  - pip install ansible-lint
  - pip install yamllint
  - pip install molecule
  - pip install molecule-docker
  - pip install testinfra
script:
  - travis_wait molecule test -s travis

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
