---
- name: Install apt package for lang-ja
  apt:
    name:
      - language-pack-ja

- name: Check whether /etc/default/locale contains 'LANG=ja_JP.UTF-8'
  command: grep -Fxq 'LANG=ja_JP.UTF-8' /etc/default/locale
  register: is_default_locale_ja
  ignore_errors: yes
  changed_when: no
  failed_when: False

- name: Set system default LANG to ja_JP.UTF-8
  command: update-locale LANG=ja_JP.UTF-8
  when: is_default_locale_ja.rc != 0

- name: Set user LANGUAGE to ja_JP.UTF-8
  lineinfile:
    path: /home/vagrant/.bashrc
    line: 'export LANGUAGE=ja_JP:ja'
