---
# tasks file for pypro3
- name: Make a link for ansible_python_interpreter
  become: yes
  file:
    src: /usr/bin/python3.5
    dest: /usr/bin/python
    state: link

- name: Update and upgrade all packages to the latest version
  become: yes
  apt:
    update_cache: yes
    upgrade: yes
    cache_valid_time: 3600

- name: Install apt packages
  become: yes
  apt:
    name:
      - language-pack-ja
      - build-essential
      - python3-dev
      - libsqlite3-dev
      - libreadline6-dev
      - libgdbm-dev
      - zlib1g-dev
      - libbz2-dev
      - sqlite3
      - tk-dev
      - zip
      - libssl-dev

- name: Check whether /etc/default/locale contains 'LANG=ja_JP.UTF-8'
  command: grep -Fxq 'LANG=ja_JP.UTF-8' /etc/default/locale
  register: is_default_locale_ja
  ignore_errors: yes
  changed_when: no
  failed_when: False

- name: Set system default locale to ja_JP.UTF-8
  become: yes
  command: update-locale LANG=ja_JP.UTF-8
  when: is_default_locale_ja.rc != 0

- name: Set user locale to ja_JP.UTF-8
  lineinfile:
    path: /home/vagrant/.bashrc
    line: 'export LANGUAGE=ja_JP:ja'

- name: Download python3.6 tar ball
  become: yes
  get_url:
    url: https://www.python.org/ftp/python/3.6.4/Python-3.6.4.tgz
    dest: /opt/Python-3.6.4.tgz

- name: Unarchive python3.6 tar ball
  become: yes
  unarchive:
    src: /opt/Python-3.6.4.tgz
    dest: /opt
    remote_src: yes

- name: Install python3.6
  become: yes
  command: '{{ item }}'
  args:
    chdir: /opt/Python-3.6.4
    creates: /opt/python3.6.4/bin/python3.6
  with_items:
    - ./configure --prefix=/opt/python3.6.4
    - make
    - make install

- name: Make links for python3.6, pip to /usr/local/bin
  become: yes
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  with_items:
    - {src: /opt/python3.6.4/bin/python3.6, dest: /usr/local/bin/python3.6}
    - {src: /opt/python3.6.4/bin/pip3.6, dest: /usr/local/bin/pip}
