---
- name: Install apt packages for python3
  become: yes
  apt:
    name:
      - build-essential
      - python3-dev
      - libsqlite3-dev
      - libreadline6-dev
      - libgdbm-dev
      - zlib1g-dev
      - libbz2-dev
      - sqlite3
      - tk-dev
      - zip
      - libssl-dev

- name: Download python3.6 tar ball
  become: yes
  get_url:
    url: https://www.python.org/ftp/python/3.6.4/Python-3.6.4.tgz
    dest: /opt/Python-3.6.4.tgz

- name: Unarchive python3.6 tar ball
  become: yes
  unarchive:
    src: /opt/Python-3.6.4.tgz
    dest: /opt
    remote_src: yes

- name: Install python3.6
  become: yes
  command: '{{ item }}'
  args:
    chdir: /opt/Python-3.6.4
    creates: /opt/python3.6.4/bin/python3.6
  with_items:
    - ./configure --prefix=/opt/python3.6.4
    - make
    - make install

- name: Make links for python3.6, pip to /usr/local/bin
  become: yes
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  with_items:
    - {src: /opt/python3.6.4/bin/python3.6, dest: /usr/local/bin/python3.6}
    - {src: /opt/python3.6.4/bin/pip3.6, dest: /usr/local/bin/pip}
