---
dependency:
  name: galaxy
driver:
  name: docker
  provider:
    name: virtualbox
lint: |
  yamllint .
platforms:
  - name: instance
    image: ubuntu:16.04
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/playbooks/playbook.yml
  lint: |
    ansible-lint
verifier:
  name: testinfra
  directory: ../resources/tests/
  options:
    v: 1
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  lint: |
    flake8
